### PR TITLE
changed sectorize to create diagonal plane for first sector division

### PR DESCRIPTION
**Pull request by samuelshaner**
This PR changes the `Cell:sectorize()` method to use a diagonal plane to create the first sector division instead of a horizontal plane, as is done in CASMO:

sectorize

### CODE REVIEW

**Comment by wbinventor** [comment]
The documentation needs to be updated. The Travis build seems to fail since SWIG wasn't installed correctly for some reason. I'm going to close and then re-open to see if that triggers it to install...?

**Comment by wbinventor** [comment]
As with #275, this should be quick merge once the docs are updated and the Travis build works.

**Comment by wbinventor** [comment]
Well looks like Travis was flaking out earlier - closing and reopening triggered it to install swig correctly and the tests all pass.

**Comment by samuelshaner** [comment]
The documentation has been updated to reflect the new sectorize methodology.

**Pull request merged**
