### PR TITLE
Nu-Transport OpenMC MGXS Type in Materialize Module

### PR DESCRIPTION
**Pull request by wbinventor**
This few line PR adds the "nu-tranport" MGXS type introduced in `openmc.mgxs` in mit-crpg/openmc#644 to the `openmoc.materialize` module.

### CODE REVIEW

**Comment by geogunow** [comment]
Everything looks fine to me

**Comment by samuelshaner** [comment]
@wbinventor - can you add some commentary in `Material.cpp` and in the user's guide 'userguide/input.rst' to indicate that `_sigma_t` can be either the total, transport, or nu-transport xs?

**Comment by wbinventor** [comment]
@samuelshaner I added "nu-transport" to the docs.

**Comment by geogunow** [comment]
@wbinventor do we want to define what nu-transport means in the docs?

**Comment by wbinventor** [comment]
Perhaps in a future PR? There are lots of ways one can define transport
cross-section, and I'm not prepared to spend time writing an overview on it
for the site at the moment.

**Pull request merged**
