### PR TITLE
Fix cylinder intersections for tangent tracks

### PR DESCRIPTION
**Pull request by GiudGiud**
@K-Wone correctly pointed out a bug in the handling of tangent tracks for Z-Cylinders in #456 . 
This implements the proposed fix. 

This PR also makes the decision for whether an intersection is present or not for a tangent track more consistent, since negative rounding errors are now treated similarly as positive ones. The right EPSILON for the decision on whether there is a single intersection is ON_SURFACE_THRESH (1e-12)

This PR also removes a lot of "if" conditions on the polar directions when looking at intersections. Since the cylinder is infinite in the Z direction, there is no need to check whether the track is going up or down, it's the same with regards to the number of intersections!

This PR also adds unit tests for surfaces, ZCylinder and XYZPlanes. Those are built as subclasses of a SurfaceTests class. Those tests do include the edge case that was buggy before. 

An optimization remark: tangent tracks cut the segment in two but do not change the solution at all. They could be ignored and this would reduce the number of segments in the geometry, thus improving runtime.

### CODE REVIEW

**Comment by alephpiece** [comment]
It seems that a track with polar angle = 0 intersects the cylinder at infinity. This is true since the ZCylinder is infinite in the z direction. However, this 'infinity' here is `tan(M_PI_2)` which is actually a very large number (could be `1.63312e+16`)  rather than `INFINITY` (implementation-defined macro).

This may be harmless but rather confusing. The distance between the starting point of the track and this infinite intersection, which is a large number different from `INFINITY`, will be returned by `Surface::getMinDistance`. But I would expect an `INFINITY` whenever I believe my track intersects the cylinder at infinity if I have no kwnoledge of the implementation.

**Comment by alephpiece** [comment]
My temporary workaround for this is to reset the z coordinate.
```
if (num > 0 && (fabs(polar) < FLT_EPSILON || fabs(polar - M_PI) < FLT_EPSILON))                                                                                 
  points[0].setZ( copysign(1., points[0].getZ()) * INFINITY );
```

**Comment by GiudGiud** [comment]
Agreed this could be confusing. It would not appear in any realistic system but maybe for someone debugging a feature. 

To make things simple, we can assume that a vertical track and a Z cylinder do not intersect. 
This is also consistent with the behavior for Planes and parallel tracks

**Comment by alephpiece** [comment]
Great.

The conditions made to identify vertical tracks in `intersection` take `1e-10` as the limit. I wonder what would happen if I change the limit to `FLT_EPSILON`. I didn't see any difference between them.

**Comment by GiudGiud** [comment]
Anything that would change would involve segment lengths of 1e-10, which wont impact the solution.
I'll leave making all the epsilons consistent throughout ray tracing to another PR, and merge this one soon.

**Comment by alephpiece** [comment]
That would be great. I think it's time to close #456.

**Comment by GiudGiud** [comment]
Merged. Thanks again @K-Wone for catching this!

**Comment by alephpiece** [comment]
:)

**Pull request merged**
