### PR TITLE
Fixes and optimizations for explicit_3D ray tracing

### PR DESCRIPTION
**Pull request by GiudGiud**
Couple of small optimizations :
- segments built on the stack before being pushed_back in segment vectors
- dynamic openmp schedules. I've observed that cases with very long tracks have significant load imbalance otherwise
- getNumGroups has been moved out of the hotspot since it involves a call to getAllMaterials
- CMFD relaxation factors have better defaults, with SOR at 1.5 and Dcorr at 0.7, providing both increased speed and stability. Since these parameters are now output it's not a problem that these improvements wont always hold

Ray tracing fixes :
- resilience to floating point errors when setting track start and end points
- track linking wasn't implemented. I've added it in track segmentation, which is not ideal, but won't cause problems

Other fixes :
- more use of Progress construct, leading to more reliable estimate of a section's progress in domain decomposed cases
- more logs for CMFD memory consumption, which is larger than I expected for full core cases
- 3d track and segment plots no longer overwrite 2d ones
- zero volume source regions no longer make the CPULSSolver crash
- negative fluxes are now output in the CPULSSolver

### CODE REVIEW

**Comment by GiudGiud** [comment]
@mit-crpg/openmoc-dev anyone to review this PR ?
Explicit 3D ray tracing is not our most important feature but we cant just leave it broken if 3D MOC is going to become develop.

**Comment by GiudGiud** [comment]
This is probably going to be the last PR before the merge with develop

**Comment by GiudGiud** [comment]
Merging this Monday

**Comment by wuwenbin2006** [comment]
I tested the Explict segmentation with my examples, it worked good. I think it is good to merge. Wenbin Wu On 05/03/2019 05:23, Giud wrote: Merging this Monday — You are receiving this because you are on a team that was mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by GiudGiud** [comment]
Thanks for checking @wuwenbin2006 ! We dont plan on using this feature much. Merging!

**Pull request merged**
