### PR TITLE
[HOTFIX] Generalized Spatial Data Plotting

### PR DESCRIPTION
**Pull request by wbinventor**
This one line PR fixes a bug in the `plot_spatial_data` method to permit plotting of generic floating point data (rather than only integers).

### CODE REVIEW

**Comment by wbinventor** [comment]
I added a bug fix suggested to me by @geogunow - `TINY_MOVE` is now 1E-8 in place of 1E-10. Surprisingly, this changed some of our test results very slightly. Anyone want to review this tiny PR?

**Comment by wbinventor** [comment]
@geogunow @samuelshaner do either of you want to do the honors with this PR? I'm trying to go through and make sure all of the code necessary for my thesis is fully merged in here and elsewhere.

**Comment by samuelshaner** [comment]
Looks good to me!

**Comment by rvignolo** [comment]
Hi!

I don't think it is correcto to select a bigger tiny_move (1e-8 instead of 1e-10). For example, you could be missing the segment inside a circle if a track crosses it very tangentially. Or you could be missing segments near the center of a pin when an azimuthal discretization is used. 

Why don't you try to check that the sum of your segment lengths are equal to the track length? You know exactly the track length because you know the geometry bounding box. I think i haven't seen that check inside the code... but i could be wrong.

In the other hand, you might be using the tiny_move in order to find a point x and then the element where this point lies. If you select a small tiny move, you could be finding the wrong element. But i don't think this is the reason of the differences when using 1e-8 or 1e-10.

Thank you for sharing your code and sorry for my english!

**Comment by rvignolo** [comment]
no one replied me!

**Comment by GiudGiud** [comment]
Hello

The segments we may miss will be of a length below 1e-8 (cm), so they will have no influence on the solution.
We don't routinely check that the sum of the segment lengths is equal to the track length because this is not required for MOC. I agree this is a good debug test, but the sum will be the same here, whether tiny move is 1e-10 or 1e-8.

The simple_lattice test has some segments exactly lie on azimuthal sector planes, so the change of the tiny move modified the result by changing the assignment of these segments from one FSR to another. That's why the test results changed.

**Comment by rvignolo** [comment]
Thanks for your reply @GiudGiud, very clarifying.

**Pull request merged**
