### PR TITLE
Optimized Eigenvalue Calculation

### PR DESCRIPTION
**Pull request by wbinventor**
This PR removes the calculation of the old (prior iteration's) fission source when computing the eigenvalue. This is unnecessary since the (old) flux is scaled after each power iteration such that the total (old) fission source is unity. @samuelshaner do you want to look at this since we discovered this together?

### CODE REVIEW

**Comment by samuelshaner** [comment]
Sure, I'll review it tonight.

**Comment by samuelshaner** [comment]
@wbinventor - have you been able to compile this with the intel compiler? I tried compiling with icpc on my mac and on nsecluster and was unsuccessful both places. Do you know if there are any environment variables or other things that need to be done to compile with icpc on nsecluster?

**Comment by wbinventor** [comment]
Hmm, what issue do you see with icpc? I just compiled on nsecluster with the following command:

```bash
python setup.py install --user --cc=icpc
```

If you are seeing a runtime error, note that you have to delete any track files generated with a different compiled version of the code since the FSRs are hashed differently between compilers.

**Comment by samuelshaner** [comment]
I was getting an error on NSECluser when I used ccache. Removing the `--with-ccache` option allowed me to compile. 

Everything looks good to me!

**Comment by wbinventor** [comment]
Oh yes, ccache doesn't play nice with the intel compiler. From what I recall when I put support in for ccache, it is really built around gcc (in particular, the command line args for gcc). Anyway, thanks for testing things out with our different supported compilers!

**Pull request merged**
